/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/apointments/': RouteRecordInfo<'/apointments/', '/apointments', Record<never, never>, Record<never, never>>,
    '/apointments/new/': RouteRecordInfo<'/apointments/new/', '/apointments/new', Record<never, never>, Record<never, never>>,
    '/certificates/': RouteRecordInfo<'/certificates/', '/certificates', Record<never, never>, Record<never, never>>,
    '/certificates/new/': RouteRecordInfo<'/certificates/new/', '/certificates/new', Record<never, never>, Record<never, never>>,
    '/doctors/': RouteRecordInfo<'/doctors/', '/doctors', Record<never, never>, Record<never, never>>,
    '/doctors/[id]/edit/': RouteRecordInfo<'/doctors/[id]/edit/', '/doctors/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/doctors/[id]/show/': RouteRecordInfo<'/doctors/[id]/show/', '/doctors/:id/show', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/doctors/new/': RouteRecordInfo<'/doctors/new/', '/doctors/new', Record<never, never>, Record<never, never>>,
    '/medicines/': RouteRecordInfo<'/medicines/', '/medicines', Record<never, never>, Record<never, never>>,
    '/medicines/[id]/edit/': RouteRecordInfo<'/medicines/[id]/edit/', '/medicines/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/medicines/[id]/show/': RouteRecordInfo<'/medicines/[id]/show/', '/medicines/:id/show', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/medicines/new/': RouteRecordInfo<'/medicines/new/', '/medicines/new', Record<never, never>, Record<never, never>>,
    '/patients/': RouteRecordInfo<'/patients/', '/patients', Record<never, never>, Record<never, never>>,
    '/patients/[id]/edit/': RouteRecordInfo<'/patients/[id]/edit/', '/patients/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/patients/[id]/show/': RouteRecordInfo<'/patients/[id]/show/', '/patients/:id/show', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/patients/new/': RouteRecordInfo<'/patients/new/', '/patients/new', Record<never, never>, Record<never, never>>,
    '/patients/view/': RouteRecordInfo<'/patients/view/', '/patients/view', Record<never, never>, Record<never, never>>,
    '/prescriptions/': RouteRecordInfo<'/prescriptions/', '/prescriptions', Record<never, never>, Record<never, never>>,
    '/prescriptions/[id]/edit/': RouteRecordInfo<'/prescriptions/[id]/edit/', '/prescriptions/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/prescriptions/[id]/show/': RouteRecordInfo<'/prescriptions/[id]/show/', '/prescriptions/:id/show', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/prescriptions/new/': RouteRecordInfo<'/prescriptions/new/', '/prescriptions/new', Record<never, never>, Record<never, never>>,
  }
}
