/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/doctors/': RouteRecordInfo<'/doctors/', '/doctors', Record<never, never>, Record<never, never>>,
    '/doctors/new/': RouteRecordInfo<'/doctors/new/', '/doctors/new', Record<never, never>, Record<never, never>>,
    '/medicines/': RouteRecordInfo<'/medicines/', '/medicines', Record<never, never>, Record<never, never>>,
    '/medicines/new/': RouteRecordInfo<'/medicines/new/', '/medicines/new', Record<never, never>, Record<never, never>>,
    '/patients/': RouteRecordInfo<'/patients/', '/patients', Record<never, never>, Record<never, never>>,
    '/patients/new/': RouteRecordInfo<'/patients/new/', '/patients/new', Record<never, never>, Record<never, never>>,
  }
}
